apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
        - name: config-volume
          configMap:
            name: logoutput-configmap
            items:
              - key: information.txt
                path: information.txt
      containers:
        - name: logoutput-generator
          image: tomaspedroso/logoutput-generator
          volumeMounts:
            - name: shared-logs
              mountPath: /shared
        - name: logoutput-webserver
          image: tomaspedroso/logoutput-webserver
          volumeMounts:
            - name: shared-logs
              mountPath: /shared
            - name: config-volume
              mountPath: /config
          env:
            - name: PORT
              value: "3000"
            - name: PING_PONG_URL
              value: "http://pingpong-svc:1003"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: logoutput-configmap
                  key: MESSAGE
