apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
      containers:
        - name: logoutput-generator
          image: tomaspedroso/logoutput-generator
          volumeMounts:
            - name: shared-logs
              mountPath: /shared
        - name: logoutput-webserver
          image: tomaspedroso/logoutput-webserver
          volumeMounts:
            - name: shared-logs
              mountPath: /shared
          env:
            - name: PORT
              value: "3000"
            - name: PING_PONG_URL
              value: "http://pingpong-svc:1003"
