apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: logoutput-svc
spec:
  type: ClusterIP
  selector:
    app: logoutput
  ports:
    - port: 1001
      protocol: TCP
      targetPort: 3000
