apiVersion: v1
kind: Secret
metadata:
    namespace: exercises
    name: pingpong-secrets
data:
    DATABASE_URL: ENC[AES256_GCM,data:7cjW8hg3MDGggjiNYexUlyxaLIwRYK5SSYDfocMptdGOzwdk5FKTGAwoD0qZtOOc4gHEXsXtYK3g+NujNuHkdqskCikDnT40SgPA6pEPs5U=,iv:eJ3ot+ynAXQfyWHXLalBFABneCr1gvOLZmpg+n/NpcE=,tag:FzWeLdt+o4C1HmGMuZ/9Nw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Tjk3U3ZLYUMyT29taFQ3
            cGozbG9GdnRQUG1aVjc4Z1FzTmJWdkZNTGhjClpCNWhZQ3I5RnhTYnZMak81RnY5
            cXZBNko5Uy8zcC95RHE2V3dPTk5RNTgKLS0tIGtnOEZxOEhITVUyV0hhUzVRbFRq
            cmsxM3VqUkMvTElsUXNwcVdkb1puMG8KddV5Msb9vtCUT3Cw1k7+Rg/KBsC2Tf6Y
            5kWe+dyF56vHauSq9LswwOtCkrYR+R/wcbuXSuy7PQarlVSchSON2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q0l5wt335h6c9xc9vw8n9d95xyumtgf4wszgqjjg5p76un2hs52s37vn0w
    encrypted_regex: ^(data)$
    lastmodified: "2026-06-28T18:32:41Z"
    mac: ENC[AES256_GCM,data:/r7fGbNcI8en8cCsGljC4gbqGwHa8oxHAmIlg1SXaWfD1eM7x2eNfh+2o7riKj9VxtOyQ+r9pQG9KUH8ZotiDTDxMM4CgsXKb3w0Nj0MQIjiU9N4lX7sXmYL7CjoWdwbdzMufjcG5hzTMhudhSBoYYYPqIcb7g7Yg9hUwPHYd9k=,iv:I8Z9AdjMxIfKvmHON0wnVFhlIDxKBR2QRjbS8syYbMs=,tag:JC5LAOtV/HX3gagNBthBIQ==,type:str]
    version: 3.13.1
