apiVersion: v1
kind: Secret
metadata:
    namespace: exercises
    name: pingpong-pg-secrets
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Zs/rZkv3O1E=,iv:C+7uSdaWMwAjJ7ar/DSmxd/KSuKsqIMlx9/omd7EARk=,tag:EyZA77sb73KX4dbItmeavg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cmtwREhmOUVIM2dBYUVW
            VjA3MGlpMjVaWW1WOUtXb0FqUVVpdU1aZm40CmZuUGRBWWMvSWUrYlJUWWpIVVVy
            MDk3M3VpYkU5c2JXMlMzQklDVzA3L1UKLS0tIFd0TnhVR1NoOE8vVUVCb3BONFRM
            ekxaSnVMSS9qZzhiVkNzOURVVjhna0kKquf/p9NIC3FLQmqGKQtzhWoBUBja0Ef3
            LlUsniNxYeYlgupohXe1U1XHUkwhl2XJECVXKYQRtpBvejgs6HNeWg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q0l5wt335h6c9xc9vw8n9d95xyumtgf4wszgqjjg5p76un2hs52s37vn0w
    encrypted_regex: ^(data)$
    lastmodified: "2026-06-28T17:37:44Z"
    mac: ENC[AES256_GCM,data:4TktGQzRFN8R21aRc8jZSTiDlIiitMYpp4y+zBIWXqUsxQJoLEoRbEP7fGzeGEUn3smPGlmOpJWl4GZ/gzEYVJDEXhG1E4h78R8E/DlUdvrT/9U4BNq1T1EKcDTK6La7AD0Y7lPB7g/4QRMAZxCO6GHO9KTTP410tDW6P9kJe9w=,iv:Ze03833NLd4Hbyloh3IBpPTpSu2YmFdBskTFyDJhxE4=,tag:nzwPsq/8vsI65Y8n5ESIXg==,type:str]
    version: 3.13.1
