apiVersion: v1
kind: Secret
metadata:
    namespace: project
    name: todo-backend-secrets
data:
    DATABASE_URL: ENC[AES256_GCM,data:8VYulVpfb8Nnh3c+pUtRpRUtI4v22GfUGe42PMUCjc0M9lJYwGej2jkxW8DF/dCAfwwviicQOp3K2tfubsVfr5/+GatqPGfR,iv:hfDVzSwDFsD2JsGuVqplf+YRGZY/rG2sNKM8g3sYd2g=,tag:yErGB8rpm/i123PhwVAAjA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTjJET2RSaWdONk5Qb2ZM
            NWtrQjJCM1lzTWFZZkJWOGk4OFBMdzl4NVZNCkgxY0NZRlRwRnVrVnl2U3dVNlEx
            TmR3QTQrL0Fsbm9oY3ZqY3RNQkNLclUKLS0tIFR1M21lMGlzVFNwWEpGVXU4bWd2
            S1MySWNqalR1THF5L3dtYmZHYXpZaUEKbap+8vECwNzCltkdMMhuW3Obct2KBpep
            lsPACNxOejk1VIQWhw9EXxVLryTXOAH+G3jT2PLZh/hZqPrWN6C/4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q0l5wt335h6c9xc9vw8n9d95xyumtgf4wszgqjjg5p76un2hs52s37vn0w
    encrypted_regex: ^(data)$
    lastmodified: "2026-06-29T12:34:01Z"
    mac: ENC[AES256_GCM,data:wU8zgspdW5rjkAYWRnRymyU+x7lxhzRtO6T7PLe2vo3ESZ976NPIAM3mZCpbPVhIIOTrNzQnDU63RczH2XgybzDpJ6TshSMeJa+rmkP+Oa3u0QEMQHgjqF9aBG0ZakGB+bWAGWsTI/wLSt8qK/ChQx6vnbyeKOkVgJztXom5kGM=,iv:G9+nFNwyhUF51Kwjau3oazqjDjh0Z64BGnNBCvfUu7w=,tag:GwJ+aaJXEMDbw9kr7HBzVA==,type:str]
    version: 3.13.1
