apiVersion: v1
kind: Secret
metadata:
    namespace: project
    name: todo-pg-secrets
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:2wkeRIQJh6s=,iv:ljiOkmAuDmlNbJppw23CtBijh9VNakrQmIUfVDacOSw=,tag:BxDAqQ1SULqv8AOBSLPUUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2T0JzcG1FNEMxQjNjVS85
            UWc0QUtPbkcwQlI0Mmc1MDJZMXI2bTIrRGtZClJxQnczZVAxd3VNcmJCWk9ML1VC
            RkhGWkkxbEZEdGlodXlzbGlmL1BENWMKLS0tIGhqR04ydmFOQ2FQVTNWTmNKNHM2
            bEswOVZpQWpwWUpoTk51OUVaNmttV3cKjnT2vCOXRVIfDXE48cImDLCUZ+KVsglL
            4XNuo28DfuSI3/WADBL1GwGzHdPOypEB+pzIVoSretnGwsS9W0EHIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1q0l5wt335h6c9xc9vw8n9d95xyumtgf4wszgqjjg5p76un2hs52s37vn0w
    encrypted_regex: ^(data)$
    lastmodified: "2026-06-29T12:25:30Z"
    mac: ENC[AES256_GCM,data:dlqQkasnLU2fhBLsN+AKpBiN3mGy1cO5z7Wz2mJz+d4Ormgw20OV6Y83nS9ouedGY8xSSjYEIi0OnIELDgGrejO5ri/XxEqzgEP6R8yKi56yK42FBlvekS0abwldVKXr9BKR3HjbLcav0jjLr79mVm99cFr4cfOrOpslBn8pZ/s=,iv:U9lSuHKgRPyE+jhxXi7rN1CeLdVZqfKg+4fHP/YU7SI=,tag:yam8DjDL0zbGS7Gx+WMpfA==,type:str]
    version: 3.13.1
